// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiomglpaumuuwqdpdvip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpb21nbHBhdW11dXdxZHBkdmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NTUwODMsImV4cCI6MjA1NDQzMTA4M30.MMTchLGMkIE1v9cMfqvL1HJRuNg3kb57zKXcoDROK5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);